import { msg } from '@/constants';
import { ISocialMediaLink } from '@/interfaces';
export const socialMediaLinks: ISocialMediaLink[] = [
  {
    id: 1,
    platformName: 'Facebook',
    mdiIcon: 'mdi-facebook',
    url: 'https://www.facebook.com/@KeresztesZsolt.kzs',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@KeresztesZsolt.kzs',
    shortDescription: 'Follow us on Facebook',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_FACEBOOK,
  },
  {
    id: 2,
    platformName: 'LinkedIn',
    mdiIcon: 'mdi-linkedin',
    url: 'https://www.linkedin.com/in/keresztes.zsolt',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@keresztes.zsolt',
    shortDescription: 'Connect with me on LinkedIn',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_LINKEDIN,
  },
  {
    id: 3,
    platformName: 'GitHub',
    mdiIcon: 'mdi-github',
    url: 'https://www.github.com/kereszteszsolt',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolt',
    shortDescription: 'Follow me on GitHub',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_GITHUB,
  },
  {
    id: 4,
    platformName: 'Twitter',
    mdiIcon: 'mdi-twitter',
    url: 'https://www.twitter.com/kereszteszsolti',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@KeresztesZsolti',
    shortDescription: 'Follow me on Twitter',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_TWITTER,
  },
  {
    id: 5,
    platformName: 'Instagram',
    mdiIcon: 'mdi-instagram',
    url: 'https://www.instagram.com/kereszteszsolt_zsk',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolt_zsk',
    shortDescription: 'Follow me on Instagram',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_INSTAGRAM,
  },
  {
    id: 6,
    platformName: 'YouTube-Hu',
    mdiIcon: 'mdi-youtube',
    url: 'https://www.youtube.com/channel/@kereszteszsolt',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolt',
    shortDescription: 'Subscribe to my YouTube channel',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_YOUTUBE,
  },
  {
    id: 7,
    platformName: 'YouTube-En',
    mdiIcon: 'mdi-youtube',
    url: 'https://www.youtube.com/channel/@kereszteszsolti',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolti',
    shortDescription: 'Subscribe to my YouTube channel',
    callToAction: msg.CLICK_AND_FALLOW_ME_ON_YOUTUBE,
  },
  {
    id: 8,
    platformName: 'Linktr.ee',
    mdiIcon: 'mdi-link-variant',
    url: 'https://www.linktr.ee/kereszteszsolt',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolt',
    shortDescription: 'Linktr.ee',
    callToAction: 'Linktr.ee',
  },
  {
    id: 9,
    platformName: 'buy-me-a-coffee',
    mdiIcon: 'mdi-coffee',
    url: 'https://www.buymeacoffee.com/kereszteszsolt',
    profileName: 'Keresztes Zsolt',
    profileIdentifier: '@kereszteszsolt',
    shortDescription: 'Support me on Buy Me A Coffee',
    callToAction: 'Support me on Buy Me A Coffee',
  }
];
